### ISSUE TITLE
PZEM004T V3.0 not compatible with this library

### ISSUE THREAD

**Issue by aksh2412** [olehs/PZEM004T#60] opened 2019-06-28 07:51 UTC
[Scan 17-Jun-2019 (1).pdf](https://github.com/olehs/PZEM004T/files/3338092/Scan.17-Jun-2019.1.pdf)
Hello,

I bought new PZEM004T V3.0 module and using this library it is was not working, on further debugging found that the command sequence for PZEM004T V3.0 and PZEM004T V1.0 are different.
Please let me know if my above observation is correct.

Also provide me with the solution as PZEM004T V3.0 requires CRC of 16 bit with 0xA001 polynomial.

Attached is user manual for PZEM004T V3.0.

Thank you,
Akshay

**Comment by RuslanKap** [comment] 2019-06-28 14:13
+

**Comment by aksh2412** [comment] 2019-06-28 18:02
Can you suggest any solution for this?

**Comment by innovators-guru** [comment] 2019-06-30 09:45
Check all details about PZEM-004T V3.0 and its library  https://innovatorsguru.com/pzem-004t-v3/

**Comment by innovators-guru** [comment] 2019-06-30 09:45
Check all details about PZEM-004T V3.0 and its library  [https://innovatorsguru.com/pzem-004t-v3/]

**Comment by SumeriLal** [comment] 2019-08-28 07:39
Use this library : https://github.com/SumeriLal/Arduino/tree/master/MasterPZEM

**Comment by mandulaj** [comment] 2019-12-17 08:17
I am in a bit of conflict of interest, but my library isn't half bad https://github.com/mandulaj/PZEM-004T-v30  :smile:

**Comment by mandulaj** [comment] 2019-12-17 08:19
Also this is a duplicate of #58

**Closed** 2020-07-25 10:27 UTC
